language: rust
script:
  - rustc --version
  - cargo --version
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - rustdoc --test README.md -L target/deps -L target
  - cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=flate2/index.html>' > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages &&
  rm target/doc/index.html &&
  mv target/doc . &&
  (curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh)
notifications:
  slack:
    secure: TkDnUuFH2gOQTLavAtpH2biJIZzsKawZgtsih+rXCn8hujDSXVSZ/TZqjIbnkjD7DLfQO6HIOI4IX/5lRnVitLCjfoo5FJUr9vnMKqRvneBUMEuvOgKQZ86FkGVHcTlSNOhgAKGFMgm0h9epMh+81AN5ExUyofXRFEaHcy7zeMo=
  email:
    on_success: never
env:
  global:
# RUSTCI_TOKEN
  - secure: PM56iFjQm0/9y2ekPNYiGj3VzvqnaRGPZmm4gOgvwWuVD9nWJt9Rs/A2Io16Yuuv+X/zUrvBb4yCafwPp8l+6vA0dRIWwJ3UF3FdQI5ocKT2lxQSVh27XTnYfd5o3kjs4/RGRgQbuOwL4d69xTrMh2QkqLeAhKlIVwEt24t3JK0=
# GH_TOKEN
  - secure: SuZ87xbxZZa9KJSFiAelJSIHg+7/ae60WNqAHRpAEmQGqOihERlpal9H6o5fgVb4VcvvYqYN1CKRVb2aX60mJocB+XAPGRGAzIxyEAEQ/pUYob209Dk9fCZpk28tQvAHJNHenx8WkUJUUtuSxfg8NC9ttZrPzPk02itYP1R9Em8=
