sudo: false
language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
rust:
  - stable
  - beta
  - nightly
  env: FEATURES="--features clippy"
script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
  - rustdoc --test README.md -L target/debug/deps -L target/debug
after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    ./kcov-master/tmp/usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/slack_hook-* &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    { [ "$TRAVIS_TAG" != "" ] || [ "$TRAVIS_BRANCH" == "master" ]; } &&
    echo '<meta http-equiv=refresh content=0;url=slack_hook/index.html>' > target/doc/index.html &&
    pip install ghp-import --user $USER &&
    $HOME/.local/bin/ghp-import -n target/doc &&
    git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages &&
    echo "\nDocs published.\n"
notifications:
  slack:
    secure: TkDnUuFH2gOQTLavAtpH2biJIZzsKawZgtsih+rXCn8hujDSXVSZ/TZqjIbnkjD7DLfQO6HIOI4IX/5lRnVitLCjfoo5FJUr9vnMKqRvneBUMEuvOgKQZ86FkGVHcTlSNOhgAKGFMgm0h9epMh+81AN5ExUyofXRFEaHcy7zeMo=
  email:
    on_success: never
env:
  global:
    - secure: SuZ87xbxZZa9KJSFiAelJSIHg+7/ae60WNqAHRpAEmQGqOihERlpal9H6o5fgVb4VcvvYqYN1CKRVb2aX60mJocB+XAPGRGAzIxyEAEQ/pUYob209Dk9fCZpk28tQvAHJNHenx8WkUJUUtuSxfg8NC9ttZrPzPk02itYP1R9Em8=
