[package]
authors = ["Christopher Brickley <brickley@gmail.com>"]
description = "A rust crate for sending messages to Slack via webhooks."
homepage = "https://github.com/frostly/rust-slack"
keywords = ["slack", "webhook", "hook", "messaging"]
license = "MIT/Apache-2.0"
name = "slack-hook"
readme = "README.md"
repository = "https://github.com/frostly/rust-slack"
version = "0.2.0"

[dependencies]
chrono = "0.2.25"
curl = ">= 0.3.0, < 0.5.0"
hex = "0.2.0"
log = "0.3.6"
quick-error = "1.1.0"
serde = "0.9.8"
serde_derive = "0.9"
serde_json = "0.9"
url_serde = "0.1.3"
url = ">= 1.2.0, < 1.5.0"

[dependencies.clippy]
optional = true
version = "^0.0"
