[package]
name = "slack-hook"
version = "0.1.0"
authors = ["Christopher Brickley <brickley@gmail.com>"]
description = "A rust crate for sending messages to Slack via webhooks."
homepage = "https://github.com/frostly/rust-slack"
repository = "https://github.com/frostly/rust-slack"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["slack", "webhook", "hook"]

[dependencies]
rustc-serialize = "*"
curl = "*"
log = "*"
