[package]
authors = ["Christopher Brickley <brickley@gmail.com>"]
description = "A rust crate for sending messages to Slack via webhooks."
homepage = "https://github.com/frostly/rust-slack"
keywords = ["slack", "webhook", "hook", "messaging"]
license = "MIT/Apache-2.0"
name = "slack-hook"
readme = "README.md"
repository = "https://github.com/frostly/rust-slack"
version = "0.1.3"

[dependencies]
curl = "0.3.0"
log = "0.3.6"
rustc-serialize = "0.3.19"

[dependencies.clippy]
optional = true
version = "^0.0"

[features]
unstable = []
